sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t elhamjahani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elhamjahani/docker-react npm run test
