sudo: required
services:
        - docker


before_install:
        - docker build -t elham/docker-react -f Dockerfile.dev .


script:
        - docker run -e CI=true elham/docker-react npm run test


